#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Create The Console Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

(new Console\Bootstrap\LoadEnvironmentVariables(
    __DIR__,
    env('APP_NAME', 'Migration Console')
))->bootstrap();

date_default_timezone_set(env('APP_TIMEZONE', 'Asia/Makassar'));

$app = new Console\Base\Application(__DIR__);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    Console\Command::class
);

/*
|--------------------------------------------------------------------------
| Run The Artisan ConsoleApplication
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make('Illuminate\Contracts\Console\Kernel');

exit($kernel->handle(
        new Symfony\Component\Console\Input\ArgvInput,
        new Symfony\Component\Console\Output\ConsoleOutput
));